spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

management:
  endpoints:
    web:
      exposure:
        include: "*"

dgs:
  reload: true
  graphql:
    websocket:
      path: /subscriptions
      connection-init-timeout: 10s